version: "3"
services:
  app:
    container_name: 'visto-arizona-app'
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: 'visto-arizona-challenge'
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
  db:
    container_name: 'visto-arizona-db'
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'visto'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - ./db:/var/lib/mysql
 