<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateCountriesTable extends Migration
{
    private const TABLE = 'countries';

    private array $countries;

    /**
     * CreateCountriesTable constructor.
     *
     */
    public function __construct()
    {
        $currentDate = '2020-11-09 00:00:00';

        $this->countries = [
            [
                'code' => 'AD',
                'name' => 'Andorra',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'AE',
                'name' => 'United Arab Emirates',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'AF',
                'name' => 'Afghanistan',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'AG',
                'name' => 'Antigua and Barbuda',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'AI',
                'name' => 'Anguilla',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'AL',
                'name' => 'Albania',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'AM',
                'name' => 'Armenia',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'AN',
                'name' => 'Netherlands Antilles',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'AO',
                'name' => 'Angola',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'AQ',
                'name' => 'Antarctica',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'AR',
                'name' => 'Argentina',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'AS',
                'name' => 'American Samoa',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'AT',
                'name' => 'Austria',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'AU',
                'name' => 'Australia',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'AW',
                'name' => 'Aruba',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'AZ',
                'name' => 'Azerbaijan',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'BA',
                'name' => 'Bosnia and Herzegovina',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'BB',
                'name' => 'Barbados',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'BD',
                'name' => 'Bangladesh',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'BE',
                'name' => 'Belgium',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'BF',
                'name' => 'Burkina Faso',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'BG',
                'name' => 'Bulgaria',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'BH',
                'name' => 'Bahrain',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'BI',
                'name' => 'Burundi',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'BJ',
                'name' => 'Benin',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'BM',
                'name' => 'Bermuda',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'BN',
                'name' => 'Brunei Darussalam',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'BO',
                'name' => 'Bolivia',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'BR',
                'name' => 'Brazil',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'BS',
                'name' => 'Bahamas',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'BT',
                'name' => 'Bhutan',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'BV',
                'name' => 'Bouvet Island',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'BW',
                'name' => 'Botswana',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'BY',
                'name' => 'Belarus',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'BZ',
                'name' => 'Belize',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'CA',
                'name' => 'Canada',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'CC',
                'name' => 'Cocos (Keeling) Islands',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'CF',
                'name' => 'Central African Republic',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'CG',
                'name' => 'Congo',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'CH',
                'name' => 'Switzerland',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'CI',
                'name' => 'Cote D\'Ivoire (Ivory Coast)',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'CK',
                'name' => 'Cook Islands',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'CL',
                'name' => 'Chile',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'CM',
                'name' => 'Cameroon',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'CN',
                'name' => 'China',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'CO',
                'name' => 'Colombia',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'CR',
                'name' => 'Costa Rica',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'CS',
                'name' => 'Czechoslovakia (former)',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'CU',
                'name' => 'Cuba',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'CV',
                'name' => 'Cape Verde',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'CX',
                'name' => 'Christmas Island',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'CY',
                'name' => 'Cyprus',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'CZ',
                'name' => 'Czech Republic',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'DE',
                'name' => 'Germany',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'DJ',
                'name' => 'Djibouti',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'DK',
                'name' => 'Denmark',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'DM',
                'name' => 'Dominica',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'DO',
                'name' => 'Dominican Republic',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'DZ',
                'name' => 'Algeria',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'EC',
                'name' => 'Ecuador',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'EE',
                'name' => 'Estonia',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'EG',
                'name' => 'Egypt',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'EH',
                'name' => 'Western Sahara',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'ER',
                'name' => 'Eritrea',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'ES',
                'name' => 'Spain',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'ET',
                'name' => 'Ethiopia',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'FI',
                'name' => 'Finland',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'FJ',
                'name' => 'Fiji',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'FK',
                'name' => 'Falkland Islands (Malvinas)',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'FM',
                'name' => 'Micronesia',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'FO',
                'name' => 'Faroe Islands',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'FR',
                'name' => 'France',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'FX',
                'name' => 'France, Metropolitan',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'GA',
                'name' => 'Gabon',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'GB',
                'name' => 'Great Britain (UK)',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'GD',
                'name' => 'Grenada',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'GE',
                'name' => 'Georgia',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'GF',
                'name' => 'French Guiana',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'GH',
                'name' => 'Ghana',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'GI',
                'name' => 'Gibraltar',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'GL',
                'name' => 'Greenland',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'GM',
                'name' => 'Gambia',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'GN',
                'name' => 'Guinea',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'GP',
                'name' => 'Guadeloupe',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'GQ',
                'name' => 'Equatorial Guinea',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'GR',
                'name' => 'Greece',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'GS',
                'name' => 'S. Georgia and S. Sandwich Isls.',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'GT',
                'name' => 'Guatemala',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'GU',
                'name' => 'Guam',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'GW',
                'name' => 'Guinea-Bissau',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'GY',
                'name' => 'Guyana',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'HK',
                'name' => 'Hong Kong',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'HM',
                'name' => 'Heard and McDonald Islands',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'HN',
                'name' => 'Honduras',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'HR',
                'name' => 'Croatia (Hrvatska)',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'HT',
                'name' => 'Haiti',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'HU',
                'name' => 'Hungary',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'ID',
                'name' => 'Indonesia',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'IE',
                'name' => 'Ireland',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'IL',
                'name' => 'Israel',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'IN',
                'name' => 'India',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'IO',
                'name' => 'British Indian Ocean Territory',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'IQ',
                'name' => 'Iraq',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'IR',
                'name' => 'Iran',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'IS',
                'name' => 'Iceland',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'IT',
                'name' => 'Italy',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'JM',
                'name' => 'Jamaica',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'JO',
                'name' => 'Jordan',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'JP',
                'name' => 'Japan',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'KE',
                'name' => 'Kenya',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'KG',
                'name' => 'Kyrgyzstan',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'KH',
                'name' => 'Cambodia',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'KI',
                'name' => 'Kiribati',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'KM',
                'name' => 'Comoros',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'KN',
                'name' => 'Saint Kitts and Nevis',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'KP',
                'name' => 'Korea (North)',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'KR',
                'name' => 'Korea (South)',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'KW',
                'name' => 'Kuwait',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'KY',
                'name' => 'Cayman Islands',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'KZ',
                'name' => 'Kazakhstan',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'LA',
                'name' => 'Laos',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'LB',
                'name' => 'Lebanon',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'LC',
                'name' => 'Saint Lucia',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'LI',
                'name' => 'Liechtenstein',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'LK',
                'name' => 'Sri Lanka',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'LR',
                'name' => 'Liberia',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'LS',
                'name' => 'Lesotho',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'LT',
                'name' => 'Lithuania',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'LU',
                'name' => 'Luxembourg',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'LV',
                'name' => 'Latvia',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'LY',
                'name' => 'Libya',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'MA',
                'name' => 'Morocco',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'MC',
                'name' => 'Monaco',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'MD',
                'name' => 'Moldova',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'MG',
                'name' => 'Madagascar',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'MH',
                'name' => 'Marshall Islands',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'MK',
                'name' => 'Macedonia',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'ML',
                'name' => 'Mali',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'MM',
                'name' => 'Myanmar',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'MN',
                'name' => 'Mongolia',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'MO',
                'name' => 'Macau',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'MP',
                'name' => 'Northern Mariana Islands',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'MQ',
                'name' => 'Martinique',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'MR',
                'name' => 'Mauritania',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'MS',
                'name' => 'Montserrat',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'MT',
                'name' => 'Malta',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'MU',
                'name' => 'Mauritius',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'MV',
                'name' => 'Maldives',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'MW',
                'name' => 'Malawi',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'MX',
                'name' => 'Mexico',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'MY',
                'name' => 'Malaysia',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'MZ',
                'name' => 'Mozambique',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'NA',
                'name' => 'Namibia',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'NC',
                'name' => 'New Caledonia',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'NE',
                'name' => 'Niger',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'NF',
                'name' => 'Norfolk Island',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'NG',
                'name' => 'Nigeria',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'NI',
                'name' => 'Nicaragua',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'NL',
                'name' => 'Netherlands',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'NO',
                'name' => 'Norway',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'NP',
                'name' => 'Nepal',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'NR',
                'name' => 'Nauru',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'NT',
                'name' => 'Neutral Zone',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'NU',
                'name' => 'Niue',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'NZ',
                'name' => 'New Zealand (Aotearoa)',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'OM',
                'name' => 'Oman',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'PA',
                'name' => 'Panama',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'PE',
                'name' => 'Peru',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'PF',
                'name' => 'French Polynesia',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'PG',
                'name' => 'Papua New Guinea',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'PH',
                'name' => 'Philippines',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'PK',
                'name' => 'Pakistan',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'PL',
                'name' => 'Poland',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'PM',
                'name' => 'St. Pierre and Miquelon',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'PN',
                'name' => 'Pitcairn',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'PR',
                'name' => 'Puerto Rico',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'PT',
                'name' => 'Portugal',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'PW',
                'name' => 'Palau',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'PY',
                'name' => 'Paraguay',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'QA',
                'name' => 'Qatar',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'RE',
                'name' => 'Reunion',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'RO',
                'name' => 'Romania',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'RU',
                'name' => 'Russian Federation',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'RW',
                'name' => 'Rwanda',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'SA',
                'name' => 'Saudi Arabia',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'Sb',
                'name' => 'Solomon Islands',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'SC',
                'name' => 'Seychelles',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'SD',
                'name' => 'Sudan',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'SE',
                'name' => 'Sweden',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'SG',
                'name' => 'Singapore',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'SH',
                'name' => 'St. Helena',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'SI',
                'name' => 'Slovenia',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'SJ',
                'name' => 'Svalbard and Jan Mayen Islands',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'SK',
                'name' => 'Slovak Republic',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'SL',
                'name' => 'Sierra Leone',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'SM',
                'name' => 'San Marino',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'SN',
                'name' => 'Senegal',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'SO',
                'name' => 'Somalia',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'SR',
                'name' => 'Suriname',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'ST',
                'name' => 'Sao Tome and Principe',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'SU',
                'name' => 'USSR (former)',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'SV',
                'name' => 'El Salvador',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'SY',
                'name' => 'Syria',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'SZ',
                'name' => 'Swaziland',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'TC',
                'name' => 'Turks and Caicos Islands',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'TD',
                'name' => 'Chad',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'TF',
                'name' => 'French Southern Territories',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'TG',
                'name' => 'Togo',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'TH',
                'name' => 'Thailand',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'TJ',
                'name' => 'Tajikistan',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'TK',
                'name' => 'Tokelau',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'TM',
                'name' => 'Turkmenistan',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'TN',
                'name' => 'Tunisia',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'TO',
                'name' => 'Tonga',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'TP',
                'name' => 'East Timor',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'TR',
                'name' => 'Turkey',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'TT',
                'name' => 'Trinidad and Tobago',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'TV',
                'name' => 'Tuvalu',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'TW',
                'name' => 'Taiwan',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'TZ',
                'name' => 'Tanzania',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'UA',
                'name' => 'Ukraine',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'UG',
                'name' => 'Uganda',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'UK',
                'name' => 'United Kingdom',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'UM',
                'name' => 'US Minor Outlying Islands',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'US',
                'name' => 'United States',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'UY',
                'name' => 'Uruguay',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'UZ',
                'name' => 'Uzbekistan',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'VA',
                'name' => 'Vatican City State (Holy See)',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'VC',
                'name' => 'Saint Vincent and the Grenadines',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'VE',
                'name' => 'Venezuela',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'VG',
                'name' => 'Virgin Islands (British)',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'VI',
                'name' => 'Virgin Islands (U.S.)',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'VN',
                'name' => 'Viet Nam',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'VU',
                'name' => 'Vanuatu',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'WF',
                'name' => 'Wallis and Futuna Islands',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'WS',
                'name' => 'Samoa',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'YE',
                'name' => 'Yemen',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'YT',
                'name' => 'Mayotte',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'YU',
                'name' => 'Yugoslavia',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'ZA',
                'name' => 'South Africa',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'ZM',
                'name' => 'Zambia',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'ZR',
                'name' => 'Zaire',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'ZW',
                'name' => 'Zimbabwe',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'COM',
                'name' => 'US Commercial',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'EDU',
                'name' => 'US Educational',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'GOV',
                'name' => 'US Government',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'INT',
                'name' => 'International',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'MIL',
                'name' => 'US Military',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'NET',
                'name' => 'Network',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'ORG',
                'name' => 'Non-Profit Organization',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'ARPA',
                'name' => 'Old style Arpanet',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'code' => 'NATO',
                'name' => 'Nato field',
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
        ];

    }

    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up(): void
    {
        Schema::create(self::TABLE, function (Blueprint $table) {
            $table->id();
            $table->string('code', 4);
            $table->string('name', 32);
            $table->timestamps();
        });

        DB::table(self::TABLE)->insert($this->countries);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down(): void
    {
        Schema::dropIfExists(self::TABLE);
    }
}
